config/routes.rb
Rails.application.routes.draw do
  get 'apis', to: "apis#index"
  get 'apis/index'
  get 'apis/typography'
  get 'static_pages/home'

  devise_for :users
  resources :typographies
  root "static_pages#home"
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    delete "sign_out", to: "devise/sessions#destroy"
  end
  resources :users, only: [:index, :edit, :update]

end

app/models/typography.rb
class Typography < ActiveRecord::Base
  belongs_to :user 
  mount_uploader :image, ImageUploader 
  # Found at app/uploaders/image_uploader.rb
  
  validates :title, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :typographies
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  def index
  @approved_codesnippets = 'Codesnippet.where(include: "yes")'
  @approved_colorpalettes = 'Colorpalette.where(include: "yes")'
  @approved_hidefimages = 'Hidefimage.where(include: "yes")'
  @approved_onepage = 'Onepage.where(include: "yes")'
  @approved_typographies = Typography.where(include: "yes")
  @approved_uxuis = 'Uxui.where(include: "yes")'
  end
  def typography
    @approved_typographies = Typography.where(include: "yes")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/typographies_controller.rb
 class TypographiesController < ApplicationController 
  before_action :set_typography, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /typographies
  # GET /typographies.json
  def index
    @typographies = Typography.all
    @approved_typographies = Typography.where(include: "yes")
    @unapproved_typographies = Typography.where(include: "no")
    @current_user = current_user
  end

  # GET /typographies/1
  # GET /typographies/1.json
  def show
  end

  # GET /typographies/new
  def new
    @typography = current_user.typographies.build
    # @typography = Typography.new
  end

  # GET /typographies/1/edit
  def edit
  end

  # POST /typographies
  # POST /typographies.json
  def create
    @typography = current_user.typographies.build(typography_params)
    # @typography = Typography.new(typography_params)

    respond_to do |format|
      if @typography.save
        format.html { redirect_to @typography, notice: 'Typography was successfully created.' }
        format.json { render :show, status: :created, location: @typography }
      else
        format.html { render :new }
        format.json { render json: @typography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /typographies/1
  # PATCH/PUT /typographies/1.json
  def update
    respond_to do |format|
      if @typography.update(typography_params)
        format.html { redirect_to @typography, notice: 'Typography was successfully updated.' }
        format.json { render :show, status: :ok, location: @typography }
      else
        format.html { render :edit }
        format.json { render json: @typography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /typographies/1
  # DELETE /typographies/1.json
  def destroy
    @typography.destroy
    respond_to do |format|
      format.html { redirect_to typographies_url, notice: 'Typography was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_typography
      @typography = Typography.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def typography_params
      params.require(:typography).permit(:title, :image, :include, :admin)
    end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :edit]
  def index
    @users = User.all
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "Successfully updated User."
      redirect_to users_path
    else
      render :action => 'edit'
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
    params.require(:user).permit(:approved)
    end

end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/typographies_helper.rb
module TypographiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apis/index.html.erb
<h1>Apis</h1>

<h2>Typographies</h2>
<% @approved_typographies.each do |content| %>
      <p>
        Title: <%= content.title %>
        Image: <%= content.image %>
      </p>
    </tr>
    <% end %>

<h2>Color Palettes</h2>
<strong>@TBC = "To be coded"</strong>
<h2>Code Snippets</h2>
<strong>@TBC = "To be coded"</strong>
<h2>Hi Def Images</h2>
<strong>@TBC = "To be coded"</strong>
<h2>Onepage</h2>
<strong>@TBC = "To be coded"</strong>
<h2>UXUI</h2>
<strong>@TBC = "To be coded"</strong>

app/views/apis/typography.html.erb
<h1>Typography</h1>
<p>This page will display the default images (1920x180) and thumb previews (640x480)</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NcwApiGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<div class="menuPanel">

     <% if user_signed_in? %>
<div class="loginBox">
    <p>You are signed in as: <%= current_user.email %></p>
    <%= link_to "sign_out", sign_out_path,  method: "delete"%>
</div>   
  <% else %>
<div class="loginBox">
    <p>You are currently not signed in</p>
    <%= link_to "sign_in", sign_in_path %>
    <%= link_to "sign_up", sign_up_path %>
</div>
  <%end %>
      <!--<strong>Content Types</strong>-->
    <div class="contentList">
      <h4>Content Types</h4>
      <ul>
        <li><%= link_to "Code Snippets", root_path %><br/></li>
        <li><%= link_to "Color Palettes", root_path %><br/></li>
        <li><%= link_to "Hi Def Images", root_path %><br/></li>
        <li><%= link_to "One Page", root_path %><br/></li>
        <li><%= link_to "Typography", typographies_path %><br/></li>
        <li><%= link_to "UxUi", root_path %><br/></li>
      </ul>
    </div>
  <div class="mainMenu">
    <h4>Main Menu</h4>
    <ul>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </div>
</div>

<div class="mainPanel">
  <div class="mainContent">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</div>


</div>
</body>
</html>

app/views/message/_apiEdit.html.erb
<strong>Note: all new APIs made by anyone who is not an admin needs to be approved first.</strong>
<p>Also, you can edit you API content if you made an error. <br>
<strong>However</strong>, once the api content is approved by an admin, API content developers cannot edit that particular API content.</p>
<p>If you see an error or need to edit an approved API content, please contact an admin.</p>

app/views/message/_noaccess.html.erb
<strong>You are not approved by an admin</strong>
  <p>Email an admin to get approval.</p>

app/views/static_pages/home.html.erb
<h1>NCW-API-GENERATOR</h1>
<p>Thanks for helping organize our API content.</p>

app/views/typographies/_adminForm.html.erb
<%= form_for(@typography) do |f| %>
  <% if @typography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@typography.errors.count, "error") %> prohibited this typography from being saved:</h2>

      <ul>
      <% @typography.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :include %><br>
    <%= f.check_box :include, {}, "yes", "no" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/typographies/_content.html.erb
<div style="border: 2px solid black; text-align:right; padding-right: 10px;">
<h2>Stats</h2>
<p>Approved: <%= @approved_typographies.count %></p>
<p>Unapproved: <%= @unapproved_typographies.count %></p>
<p>Total: <%= @typographies.count %></p>
</div>
<h1>All API Content</h1>
<table>
  <thead>
    <tr>
      <% @typographies.each do |t| %>
      <td><%= t.title %></td>
      <td>Included:<%= t.include %></td>
      <td>User email: <%= t.user.email %></td>
      <%if @current_user.admin? %>
      <td><%= link_to 'Edit', edit_typography_path(t) %></td> 
      <td><%= link_to 'Destroy', t, method: :delete, data: { confirm: 'Are you sure?' } %></td     
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% end %>

</table>

<br>
<%if @current_user.admin? %>
<h1>Admin Section | Unapproved/Awaiting Approval</h1>
<table>
  <thead>
    <tr>
      <% @unapproved_typographies.each do |t| %>
      <td><%= t.title %></td>
      <td>Included:<%= t.include %></td>
      <td><%= link_to 'Edit', edit_typography_path(t) %></td> 
      <td><%= link_to 'Destroy', t, method: :delete, data: { confirm: 'Are you sure?' } %></td     
      <th colspan="3"></th>
    </tr>
  </thead>
  <% end %>

</table>




    
  <h1>Listing Approved</h1>
      <ul>
        <% @approved_typographies.each do |t| %>
        <li><%= t.title %></li>
    <% end %>
      </ul>

  <h1>Listing Unapproved</h1>
      <ul>
        <% @unapproved_typographies.each do |t| %>
        <li><%= t.title %></li>
    <% end %>
    </ul>
<%end%>

</table>
<%= link_to 'New Typography', new_typography_path %>

app/views/typographies/_form.html.erb
<%= form_for(@typography) do |f| %>
  <% if @typography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@typography.errors.count, "error") %> prohibited this typography from being saved:</h2>

      <ul>
      <% @typography.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
  <%= f.label :include %><br>
  <%= f.check_box :include, {}, "yes", "no" %>
</div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/typographies/_uploaderForm.html.erb
<%= form_for(@typography) do |f| %>
  <% if @typography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@typography.errors.count, "error") %> prohibited this typography from being saved:</h2>

      <ul>
      <% @typography.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
   <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <% if @typography.include == "no" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% else%>
<strong>Once it's approved, you cannot edit anymore</strong>
<p>If you think there's an issue with this api, email the admin</p>
<% end %>
  
  
  
  
<% end %>

app/views/typographies/edit.html.erb
<h1>Editing Typography</h1>
<% if current_user.admin? %>
<%= render 'adminForm' %>

<%= link_to 'Show', @typography %> |
<%= link_to 'Back', typographies_path %>

<% elsif current_user.approved? %>
<%= render 'uploaderForm' %>

<% else %>
  <%= render 'message/noaccess' %>
  <%= link_to 'Back', typographies_path %>
<% end %>

app/views/typographies/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center; font-size: 2.5em;">Typography APIs</h1>
<%if !@current_user.nil? && @current_user.approved == true %>
<%= render 'content' %>
<% else %>
<%= render 'message/noaccess' %>
<% end %>

app/views/typographies/new.html.erb
<h1>New Typography</h1>
<% if current_user.admin? %>
<%= render 'adminForm' %>

<%= link_to 'Show', @typography %> |
<%= link_to 'Back', typographies_path %>

<% elsif current_user.approved? %>
<%= render 'uploaderForm' %>

<% else %>
  <%= render 'message/noaccess' %>
  <%= link_to 'Back', typographies_path %>
  <% end %>

app/views/typographies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @typography.title %>
</p>

<p>
  <strong>Include in API:</strong>
  <%= @typography.include %>
</p>

<% if !@typography.image_url %>
<strong>* This record has NO IMAGE</strong>. You need to upload an image.*
<% end %>
<h4>Thumb:</h4>
<p>
  <%= image_tag (@typography.image_url(:thumb).to_s) %>
</p>

<h4>Preview:</h4>
<p>
  <%= image_tag (@typography.image_url(:preview).to_s) %>
</p>

<h4>Full Image</h4>
<%= link_to "View in new window", @typography.image_url(:full).to_s, target: '_blank' %> <br> <br>

<%= render 'message/apiEdit' %>

<%= link_to 'Edit', edit_typography_path(@typography) %> |
<%= link_to 'Back', typographies_path %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  <%= f.label :approved %><br>
  <%= f.check_box :approved %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <% @users.each do |user| %>
      <td>
        Email: <%= user.email %>
        Approved: <%= user.approved %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td> 
      </td>
    </tr>
    <% end %>
  </thead>
</table>